config/routes.rb
Nanoblockdb::Application.routes.draw do
  resources :package_contents

  resources :packages

  resources :products

  resources :shapes

  resources :colors
  
  root to: "top#index"
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callback"
  }

  get 'amazon/search' => "products/amazon#search"
  get 'amazon/create/:asin' => "products/amazon#create"
  

end

app/models/package_content.rb
class PackageContent < ActiveRecord::Base
  belongs_to :package
end

app/controllers/package_contents_controller.rb
class PackageContentsController < ApplicationController
  before_action :set_package_content, only: [:show, :edit, :update, :destroy]

  # GET /package_contents
  # GET /package_contents.json
  def index
    @package_contents = PackageContent.all
  end

  # GET /package_contents/1
  # GET /package_contents/1.json
  def show
  end

  # GET /package_contents/new
  def new
    @package_content = PackageContent.new
  end

  # GET /package_contents/1/edit
  def edit
  end

  # POST /package_contents
  # POST /package_contents.json
  def create
    @package_content = PackageContent.new(package_content_params)

    respond_to do |format|
      if @package_content.save
        format.html { redirect_to @package_content, notice: 'Package content was successfully created.' }
        format.json { render action: 'show', status: :created, location: @package_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @package_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_contents/1
  # PATCH/PUT /package_contents/1.json
  def update
    respond_to do |format|
      if @package_content.update(package_content_params)
        format.html { redirect_to @package_content, notice: 'Package content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @package_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_contents/1
  # DELETE /package_contents/1.json
  def destroy
    @package_content.destroy
    respond_to do |format|
      format.html { redirect_to package_contents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_content
      @package_content = PackageContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_content_params
      params.require(:package_content).permit(:package_id, :color_id, :shape_id, :count)
    end
end

app/helpers/package_contents_helper.rb
module PackageContentsHelper
end

app/views/package_contents/_form.html.erb
<%= form_for(@package_content) do |f| %>
  <% if @package_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@package_content.errors.count, "error") %> prohibited this package_content from being saved:</h2>

      <ul>
      <% @package_content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.number_field :package_id %>
  </div>
  <div class="field">
    <%= f.label :color_id %><br>
    <%= f.number_field :color_id %>
  </div>
  <div class="field">
    <%= f.label :shape_id %><br>
    <%= f.number_field :shape_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_contents/edit.html.erb
<h1>Editing package_content</h1>

<%= render 'form' %>

<%= link_to 'Show', @package_content %> |
<%= link_to 'Back', package_contents_path %>

app/views/package_contents/index.html.erb
<h1>Listing package_contents</h1>

<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>Color</th>
      <th>Shape</th>
      <th>Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @package_contents.each do |package_content| %>
      <tr>
        <td><%= package_content.package_id %></td>
        <td><%= package_content.color_id %></td>
        <td><%= package_content.shape_id %></td>
        <td><%= package_content.count %></td>
        <td><%= link_to 'Show', package_content %></td>
        <td><%= link_to 'Edit', edit_package_content_path(package_content) %></td>
        <td><%= link_to 'Destroy', package_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Package content', new_package_content_path %>

app/views/package_contents/new.html.erb
<h1>New package_content</h1>

<%= render 'form' %>

<%= link_to 'Back', package_contents_path %>

app/views/package_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Package:</strong>
  <%= @package_content.package_id %>
</p>

<p>
  <strong>Color:</strong>
  <%= @package_content.color_id %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @package_content.shape_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @package_content.count %>
</p>

<%= link_to 'Edit', edit_package_content_path(@package_content) %> |
<%= link_to 'Back', package_contents_path %>