config/routes.rb
Nanoblockdb::Application.routes.draw do
  resources :package_contents

  resources :packages

  resources :products

  resources :shapes

  resources :colors
  
  root to: "top#index"
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callback"
  }

  get 'amazon/search' => "products/amazon#search"
  get 'amazon/create/:asin' => "products/amazon#create"
  

end

app/models/shape.rb
class Shape < ActiveRecord::Base
  validates :model_name, uniqueness: true

  def short_side_dot_num
   read_attribute(:short_side_dot_num) || read_attribute(:short_side_size)
  end
  def long_side_dot_num
   read_attribute(:long_side_dot_num) || read_attribute(:long_side_size)
  end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :set_shape, only: [:show, :edit, :update, :destroy]

  # GET /shapes
  # GET /shapes.json
  def index
    @shapes = Shape.all
  end

  # GET /shapes/1
  # GET /shapes/1.json
  def show
  end

  # GET /shapes/new
  def new
    @shape = Shape.new
  end

  # GET /shapes/1/edit
  def edit
  end

  # POST /shapes
  # POST /shapes.json
  def create
    @shape = Shape.new(shape_params)

    respond_to do |format|
      if @shape.save
        format.html { redirect_to @shape, notice: 'Shape was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shape }
      else
        format.html { render action: 'new' }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shapes/1
  # PATCH/PUT /shapes/1.json
  def update
    respond_to do |format|
      if @shape.update(shape_params)
        format.html { redirect_to @shape, notice: 'Shape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shapes/1
  # DELETE /shapes/1.json
  def destroy
    @shape.destroy
    respond_to do |format|
      format.html { redirect_to shapes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape
      @shape = Shape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shape_params
      params.require(:shape).permit(:name, :model_name, :image, :long_side_size, :short_side_size, :long_side_dot_num)
    end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/views/shapes/_form.html.erb
<%= form_for(@shape) do |f| %>
  <% if @shape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape.errors.count, "error") %> prohibited this shape from being saved:</h2>

      <ul>
      <% @shape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model_name %><br>
    <%= f.text_field :model_name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :long_side_size %><br>
    <%= f.number_field :long_side_size %>
  </div>
  <div class="field">
    <%= f.label :short_side_size %><br>
    <%= f.number_field :short_side_size %>
  </div>
  <div class="field">
    <%= f.label :long_side_dot_num %><br>
    <%= f.number_field :long_side_dot_num %>
  </div>
  <div class="field">
    <%= f.label :short_side_dot_num %><br>
    <%= f.number_field :short_side_dot_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shapes/edit.html.erb
<h1>Editing shape</h1>

<%= render 'form' %>

<%= link_to 'Show', @shape %> |
<%= link_to 'Back', shapes_path %>

app/views/shapes/index.html.erb
<h1>Listing shapes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model name</th>
      <th>Image</th>
      <th>Long side size</th>
      <th>Short side size</th>
      <th>Long side dot num</th>
      <th>Short side dot num</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shapes.each do |shape| %>
      <tr>
        <td><%= shape.name %></td>
        <td><%= shape.model_name %></td>
        <td><%= shape.image %></td>
        <td><%= shape.long_side_size %></td>
        <td><%= shape.short_side_size %></td>
        <td><%= shape.long_side_dot_num %></td>
        <td><%= shape.short_side_dot_num %></td>
        <td><%= link_to 'Show', shape %></td>
        <td><%= link_to 'Edit', edit_shape_path(shape) %></td>
        <td><%= link_to 'Destroy', shape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shape', new_shape_path %>

app/views/shapes/new.html.erb
<h1>New shape</h1>

<%= render 'form' %>

<%= link_to 'Back', shapes_path %>

app/views/shapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shape.name %>
</p>

<p>
  <strong>Model name:</strong>
  <%= @shape.model_name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @shape.image %>
</p>

<p>
  <strong>Long side size:</strong>
  <%= @shape.long_side_size %>
</p>

<p>
  <strong>Short side size:</strong>
  <%= @shape.short_side_size %>
</p>

<p>
  <strong>Long side dot num:</strong>
  <%= @shape.long_side_dot_num %>
</p>

<%= link_to 'Edit', edit_shape_path(@shape) %> |
<%= link_to 'Back', shapes_path %>